remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: "PortSwigger - Web Security Academy Labs"
description: >
  This page serves as my preparation guide for the Burp Practitioner exam, featuring content inspired by and derived from Burp Suite.
